name: Docker OSX Test

on:
  workflow_dispatch:

jobs:
  mac_test:
    name: Expose OSX
    runs-on: macos-13
    steps:
      - name: Expose ssh and timeout
        shell: bash
        env:
          SHUT_DOWN_IN_MINS: ${{ vars.SHUTDOWN_IN_MINUTES }}
          SSH_CLIENT_PUBLIC_KEY: ${{ secrets.SSH_CLIENT_PUBLIC_KEY }}
        run: |
          echo $SHUT_DOWN_IN_MINS
          sudo systemsetup -setremotelogin on
          echo $whoami
          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
          if ! echo $? -eq 0 ; then
            echo "SSH Key generation failed. Exiting..."
            exit 1
          fi
          echo "SSH Keys generated successfully"
          echo $SSH_CLIENT_PUBLIC_KEY >> ~/.ssh/authorized_keys
          echo "The system will shut down in: $SHUT_DOWN_IN_MINS minutes"
          echo "Use $(whoami)@$(curl ifconfig.me) to authenticate"
          echo "Shutdown in $SHUT_DOWN_IN_MINS minutes"
          python -c "import os; int(os.getenv('SHUT_DOWN_IN_MINS', 30)) * 60"
          echo $(python -c "import os; int(os.getenv('SHUT_DOWN_IN_MINS', 30)) * 60")
          sleep $(python -c "import os; int(os.getenv('SHUT_DOWN_IN_MINS', 30)) * 60")
          sudo shutdown -s now
